[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/calc/:slug"
  to = "/.netlify/functions/preview?slug=:slug"
  status = 200
  force = true
  headers = {Cache-Control = "s-maxage=3600, stale-while-revalidate"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
